### ISSUE TITLE
Interact "E" doesn't work!

### ISSUE THREAD

**Issue by PaulNevada** [gunstarpl/Shooting-Character-05-2017#1]
What's wrong here???

**Comment by doanamo** [comment]
You have to be close enough to an actor in order to interact. Please see [this](https://github.com/gunstarpl/Shooting-Character-05-2017/blob/d6c605144a8e3dae099f7ab0a102853a751a29a8/Source/Game/Characters/CharacterBase.cpp#L186).

**Comment by PaulNevada** [comment]
I am close!!! Something's really wrong here... What I need to say - I use different UE4 - 4.18.3 version...

**Comment by PaulNevada** [comment]
I've just downloaded 4.16 and the issue still remains the same... I can show you how it goes via anydesk!

// Check if the actor is an item.
	AItemBase* Item = Cast<AItemBase>(Actor);

I see it doesn't work! The whole code below is not working after that string #192...

**Comment by paulnevada1983** [comment]
| Name | Value | Type
-- | -- | -- | --
  | Item | identifier "Item" is undefined |  

The Debugger says...

**Comment by doanamo** [comment]
I've just tried running the project in UE 4.21 and everything works for me as expected.

If the cast fails and returns null, then you may be trying to interact with an object that is not derived from AItemBase. To clarify, interaction feature is limited to picking up and dropping weapons, which are the only 'items' implemented in the demo.

**Comment by PaulNevada** [comment]
I can’t understand - what to do? I use your project ‘as is’ and it doesn’t work for me. Nothing’s been changed by me at all! Help me, please.

**Comment by PaulNevada** [comment]
Can you try the project from here exactly??? Not from your machine and by downloading it from github.

**Comment by PaulNevada** [comment]
I'm sure your project here has some bug. Check it, please.

**Comment by PaulNevada** [comment]
God! I've found what I was missing!!! I need to use mouse cursor to pick up the weapon - right?!! And why is it so you made it??? I've got it FINALLY by watching you gameplay video for about 15 times...

**Comment by doanamo** [comment]
I am glad you figured it out. :)

Method that does the raycast and checks for actors under the cursor can be found [here](https://github.com/gunstarpl/Shooting-Character-05-2017/blob/d6c605144a8e3dae099f7ab0a102853a751a29a8/Source/Game/Gameplay/PlayerControllerDefault.cpp#L90).

**Comment by PaulNevada** [comment]
And is it possible to do it without the mouse cursor at all? :)

**Comment by PaulNevada** [comment]
Also, what course can you recommend for the people like me who is a real beginner in UE4 and c++?

**Comment by PaulNevada** [comment]
Thank you!

**Comment by doanamo** [comment]
Making interaction work without mouse cursor would be possible by making a character search for actors around him and finding the closest one that can be interacted with.

I recommend tutorials on Udemy that cover both UE4 with C++. This one seems very popular if you want to dive into the programming side of Unreal Engine: https://www.udemy.com/unrealcourse/

**Comment by PaulNevada** [comment]
Yeah, I see... And is that project made all by you? Also, how and what you learnt to make it?

**Comment by doanamo** [comment]
I did all the coding myself and used free Unreal assets for animation and models. I've been programming in C++ for a long time, so I could learn Unreal quickly by just reading the official documentation and the engine's source code. For starters, I recommend the Udemy course I've linked above, as it contains a lot of essentials and more. After you finish it, you will have a perfect understanding (even better than mine) of what's going on here. :)

**Comment by PaulNevada** [comment]
Yep, thanks a lot for talking :)
PS: I thank you again for your project - I really loved it. It's very alike to my beloved Unreal Engine game and I was alsways wondering to look into its code... :):):)

**Comment by doanamo** [comment]
No problem! Let me know here if anything from this project needs explaining. :)

**Comment by PaulNevada** [comment]
Thanks a lot again...

**Comment by PaulNevada** [comment]
Got a question, Piotr. How was the camera tuned? Can I place it my way?
